---
blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: "https://github.com/bob-builds-labs/bob-builds-labs.github.io/discussions"
    about: >-
      Having trouble working with the examples? Join the discussions to ask and
      answer questions in the community.
